# Generated by Django 3.2.8 on 2022-02-01 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0002_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='current',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='link',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='total',
        ),
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='queue_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='token',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='voter_id',
            field=models.CharField(default=23, max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('current', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('link', models.URLField(max_length=5000)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='solution.branch'),
            preserve_default=False,
        ),
    ]
