# Generated by Django 3.2.9 on 2022-02-07 08:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0004_member_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='code',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
